# 16-bit Addition in 8085
# Using 8-bit Operations

# Loading Data in respective registers 
MVI B, 10H
MVI C, F1H 
MVI D, A0H
MVI E, 50H

# Addition on Lower Nibble
# Storing the Value of Register C, in register A
MOV A, C
# Performing addition using ADD Instruction
ADD E
# Storing the Value of Register A in Register L
MOV L, A

# Addition on Higher Nibble
# Storing the Value of Register B, in register A
MOV A, B
# Performing addition using ADC Instruction.
# ADC will basically ADD both the higher nibbles and also carry generated by lower nibble addition
ADC D
# Storing the Value of Register A in Register H
MOV H, A

HLT
